byte b = 1;
short shortNumber = 1000;
int integer = -10;
long longNumber = 1000000;
sbyte sbyteNumber = -1;
ushort shortNumberTwo = 1000;
uint posInt = 100;
ulong longg = 10000000000;
char letter = 'a';
string msg = "hello world";
float floatNumber = 0.1f;
double doubleNumber = 0.123;
decimal decimalNumber = 0.1123221m;
bool bruh = false;

Console.WriteLine(b);
Console.WriteLine(shortNumber);
Console.WriteLine(integer);
Console.WriteLine(longNumber);
Console.WriteLine(sbyteNumber);
Console.WriteLine(shortNumberTwo);
Console.WriteLine(posInt);
Console.WriteLine(longg);
Console.WriteLine(letter);
Console.WriteLine(msg);
Console.WriteLine(floatNumber);
Console.WriteLine(doubleNumber);
Console.WriteLine(decimalNumber);
Console.WriteLine(bruh);